name: block_app
description: A Flutter plugin for blocking access to other apps on Android.
homepage: https://github.com/fadilhim/block_app
repository: https://github.com/fadilhim/block_app
version: 0.0.1

platforms:
  android:

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3
  lints: ^5.0.0
  test: ^1.24.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.block_app
        pluginClass: BlockAppPlugin