name: block_app
description: A Flutter package for managing app blocking functionality.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2
  flutter: ">=3.18.0-18.0.pre.54"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.24.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.block_app
        pluginClass: BlockAppPlugin